services:
  langflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langflow
    restart: unless-stopped
    ports:
      - "${VPN_IP}:7860:7860"
    environment:
      - LANGFLOW_PORT=7860
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_DATABASE_URL=sqlite:////app/data/langflow.db
      - LANGFLOW_CONFIG_DIR=/app/data
      - LANGFLOW_SAVE_DB_IN_CONFIG_DIR=true
      - LANGFLOW_AUTO_LOGIN=${LANGFLOW_AUTO_LOGIN}
      - LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY}
      - LANGFLOW_SUPERUSER=${LANGFLOW_SUPERUSER}
      - LANGFLOW_SUPERUSER_PASSWORD=${LANGFLOW_SUPERUSER_PASSWORD}
      - DO_NOT_TRACK=true
      - BACKEND_ONLY=false
    volumes:
      - ./data:/app/data
      - ./prompts:/app/prompts:ro
      - ./email_templates:/app/email_templates:ro
      - ./schema:/app/schema:ro
      - ./lang.json:/app/lang.json:ro
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
