services:
  n8n:
    image: ghcr.io/${GITHUB_REPOSITORY:-materiatek/materials-library-extraction}/v0-initial-flow:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      # Core n8n configuration
      - N8N_EDITOR_BASE_URL=http://127.0.0.1:5678
      - N8N_USER_FOLDER=/home/node/data
      - N8N_DISABLE_EXTERNAL_REQUIRE=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - GENERIC_TIMEZONE=UTC
      
      # Database configuration
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/data/database.sqlite
      
      # Security settings
      - N8N_SECURE_COOKIE=false
      - N8N_METRICS=false
      
      # Sensitive credentials from GitHub Secrets (injected at deployment)
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - IMAP_USER=${EMAIL_USER}
      - IMAP_PASSWORD=${EMAIL_PASS}
      - SMTP_USER=${EMAIL_USER}
      - SMTP_PASSWORD=${EMAIL_PASS}
      - SMTP_FROM=${EMAIL_USER}
      - LLM_API_KEY=${LLM_API_KEY}
      
    volumes:
      # Data persistence
      - ./data:/home/node/data
      
      # Mount prompt and template directories
      - ./prompts:/home/node/prompts:ro
      - ./email_templates:/home/node/email_templates:ro
      
      # Mount specs for reference
      - ../specs:/home/node/specs:ro
      
    env_file:
      - .env
      
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
