services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      # Core n8n configuration
      - N8N_EDITOR_BASE_URL=http://127.0.0.1:5678
      - N8N_USER_FOLDER=/home/node/data
      - N8N_DISABLE_EXTERNAL_REQUIRE=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - GENERIC_TIMEZONE=UTC
      
      # Database configuration
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/data/database.sqlite
      
      # Security settings
      - N8N_SECURE_COOKIE=false
      - N8N_METRICS=false
      
    volumes:
      # Data persistence
      - ./data:/home/node/data
      
      # Mount prompt and template directories
      - ./prompts:/home/node/prompts:ro
      - ./email_templates:/home/node/email_templates:ro
      - ./schema:/home/node/schema:ro
      
    env_file:
      - .env
      
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
