services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${VPN_IP}:5678:5678"
    environment:
      - N8N_EDITOR_BASE_URL=http://${VPN_IP}:5678
      - N8N_USER_FOLDER=/home/node/data
      - N8N_DISABLE_EXTERNAL_REQUIRE=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - GENERIC_TIMEZONE=UTC
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/data/database.sqlite
      - N8N_SECURE_COOKIE=false
      - N8N_METRICS=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./data:/home/node/data
      - ./n8n.json:/home/node/data/n8n.json:ro
      - ./prompts:/data/prompts:ro
      - ./email_templates:/data/email_templates:ro
      - ./schema:/data/schema:ro
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:5678/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
