services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${VPN_IP}:5678:5678"
    environment:
      - N8N_EDITOR_BASE_URL=http://${VPN_IP}:5678
      - N8N_USER_FOLDER=/home/node/data
      - N8N_DISABLE_EXTERNAL_REQUIRE=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - GENERIC_TIMEZONE=UTC
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/data/database.sqlite
      - N8N_SECURE_COOKIE=false
      - N8N_METRICS=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./data:/home/node/data
      - ./n8n-python.json:/home/node/data/n8n-python.json:ro
      - /tmp/n8n/attachments:/tmp/n8n/attachments
    env_file:
      - .env

  python-api:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-api
    restart: unless-stopped
    ports:
      - "${VPN_IP}:8000:8000"
    volumes:
      - ./python:/python:ro
      - ./prompts:/data/prompts:ro
      - ./email_templates:/data/email_templates:ro
      - ./schema:/data/schema:ro
      - /tmp/n8n/attachments:/tmp/n8n/attachments
      - ./data:/home/node/data
    env_file:
      - .env
