name: Validate Outputs

on:
  push:
    paths:
      - 'samples/**'
      - '**.py'
  pull_request:
    paths:
      - 'samples/**'
      - '**.py'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install jsonschema

      - name: Validate Python formatting
        run: |
          python -m compileall .

      - name: Check for schema validity in sample outputs
        run: |
          for f in samples/*_output.json; do
            echo "Validating $f"
            python -m json.tool "$f" > /dev/null
          done